### ISSUE TITLE
Requests to UpdateAdGroups fail starting on non-zero key

### ISSUE THREAD

**Issue by nathanheffley** [BingAds/BingAds-PHP-SDK#104]
I ran into a very odd bug where sending a request to Update Ad Groups will go through successfully if I send a request where the ad groups array has a zero key:
<img width="806" alt="Screen Shot 2019-08-01 at 10 14 28 AM" src="https://user-images.githubusercontent.com/8952123/62303442-1edeac80-b44a-11e9-9bf1-93be0e001740.png">

But the exact same request will fail if I set the key to be something other than zero:
<img width="807" alt="Screen Shot 2019-08-01 at 10 15 50 AM" src="https://user-images.githubusercontent.com/8952123/62303445-21410680-b44a-11e9-9f09-a5288b03b60e.png">

That fails and says that the error occurred because the `AdGroups array should not be null or empty.` This is quite odd because the ad group array is clearly not empty.

This is quite easy to replicate. Simply set the ad groups array in an Update Ad Groups Request to be an array of ad groups, none of which have `0` as their key. When you send the request it will fail with the error about a null or empty ad group array.

**Comment by eric-urban** [comment]
@nathanheffley yes I can repro the same. The library uses [SoapClient here](https://github.com/BingAds/BingAds-PHP-SDK/blob/master/src/Auth/ServiceClient.php#L271), although I didn't find any options to modify this behavior. Of course as you mentioned the solution is to always set the first list item. In a test, I could even set it null for partial success.

```php
$adGroups[] = null;
$adGroups[] = null;
$adGroups[2] = $adGroup;
```

var_dump:

```
array(3) {
  [0]=>
  NULL
  [1]=>
  NULL
  [2]=>
  object(Microsoft\BingAds\V13\CampaignManagement\AdGroup)#72 (17) {
    ["AdRotation"]=>
    NULL
    ["AudienceAdsBidAdjustment"]=>
    NULL
    ["BiddingScheme"]=>
    NULL
    ["CpcBid"]=>
    NULL
    ["EndDate"]=>
    NULL
    ["FinalUrlSuffix"]=>
    NULL
    ["ForwardCompatibilityMap"]=>
    NULL
    ["Id"]=>
    int(12345)
    ["Language"]=>
    NULL
    ["Name"]=>
    string(19) "Updated Shoe Sale"
    ["Network"]=>
    NULL
    ["PrivacyStatus"]=>
    NULL
    ["Settings"]=>
    NULL
    ["StartDate"]=>
    NULL
    ["Status"]=>
    NULL
    ["TrackingUrlTemplate"]=>
    NULL
    ["UrlCustomParameters"]=>
    NULL
  }
}
```

SOAP request:

```xml
<ns1:UpdateAdGroupsRequest>
	<ns1:CampaignId>123</ns1:CampaignId>
	<ns1:AdGroups>
		<ns1:AdGroup xsi:nil="true"/>
		<ns1:AdGroup xsi:nil="true"/>
		<ns1:AdGroup>
			<ns1:AdRotation xsi:nil="true"/>
			<ns1:AudienceAdsBidAdjustment xsi:nil="true"/>
			<ns1:BiddingScheme xsi:nil="true"/>
			<ns1:CpcBid xsi:nil="true"/>
			<ns1:EndDate xsi:nil="true"/>
			<ns1:FinalUrlSuffix xsi:nil="true"/>
			<ns1:ForwardCompatibilityMap xsi:nil="true"/>
			<ns1:Id>12345</ns1:Id>
			<ns1:Language xsi:nil="true"/>
			<ns1:Name>Updated Shoe Sale</ns1:Name>
			<ns1:Network xsi:nil="true"/>
			<ns1:PrivacyStatus xsi:nil="true"/>
			<ns1:Settings xsi:nil="true"/>
			<ns1:StartDate xsi:nil="true"/>
			<ns1:Status xsi:nil="true"/>
			<ns1:TrackingUrlTemplate xsi:nil="true"/>
			<ns1:UrlCustomParameters xsi:nil="true"/>
		</ns1:AdGroup>
	</ns1:AdGroups>
	<ns1:ReturnInheritedBidStrategyTypes xsi:nil="true"/>
</ns1:UpdateAdGroupsRequest>
```

SOAP response:

```xml
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Header>
      <h:TrackingId xmlns:h="https://bingads.microsoft.com/CampaignManagement/v13">b33273ee-f487-4e53-98e8-315604160062</h:TrackingId>
   </s:Header>
   <s:Body>
      <UpdateAdGroupsResponse xmlns="https://bingads.microsoft.com/CampaignManagement/v13">
         <InheritedBidStrategyTypes i:nil="true" xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"/>
         <PartialErrors xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
            <BatchError>
               <Code>1200</Code>
               <Details i:nil="true"/>
               <ErrorCode>CampaignServiceNullAdGroup</ErrorCode>
               <FieldPath i:nil="true"/>
               <ForwardCompatibilityMap i:nil="true" xmlns:a="http://schemas.datacontract.org/2004/07/System.Collections.Generic"/>
               <Index>0</Index>
               <Message>AdGroup is null.</Message>
               <Type>BatchError</Type>
            </BatchError>
            <BatchError>
               <Code>1200</Code>
               <Details i:nil="true"/>
               <ErrorCode>CampaignServiceNullAdGroup</ErrorCode>
               <FieldPath i:nil="true"/>
               <ForwardCompatibilityMap i:nil="true" xmlns:a="http://schemas.datacontract.org/2004/07/System.Collections.Generic"/>
               <Index>1</Index>
               <Message>AdGroup is null.</Message>
               <Type>BatchError</Type>
            </BatchError>
         </PartialErrors>
      </UpdateAdGroupsResponse>
   </s:Body>
</s:Envelope>
```

Although two null list items failed, the 3rd was updated successfully (I confirmed in the Microsoft Advertising web application).

I hope this helps!

**Comment by nathanheffley** [comment]
I've looked into it a bit more and have determined that there probably isn't a fix for this in regards to the library itself since the offending code (which checks to see if an array is empty by specifically looking at the `0` index) is generated automatically. If there is a way the code generation could be improved to actually check if the array is empty I would be more than happy to look into it, but as for this issue/repo specifically I don't think there's anything else that can be done.
