### ISSUE TITLE
Report columns CampaignPerformanceReportColumn::CampaignLabels only return Label names.

### ISSUE THREAD

**Issue by WouterVeen** [BingAds/BingAds-PHP-SDK#109]
When adding CampaignPerformanceReportColumn::CampaignLabels to a CampaignPerformanceReport I only get the names of the labels and not the descriptions. Is it possible to get the Label description in a report.

**Comment by eric-urban** [comment]
@WouterVeen I suggest please submit a [Microsoft Advertising feature suggestion](https://microsoftadvertising.uservoice.com/forums/82363-microsoft-advertising-feature-suggestions). The label description would need to be added to both UI and API.
