### ISSUE TITLE
ReportTimePeriod::ThisMonth does not work

### ISSUE THREAD

**Issue by Smartsasse** [BingAds/BingAds-PHP-SDK#111]
I am unable to use ReportTimePeriod::ThisMonth and ReportTimePeriod::Today. Can't specify dates manually if setting CustomDateRangeEnd to today or any future date.

What I'm trying to do is get the total spend for an account from beginning of current month up to yesterday but have trouble because of timezones so ReportTimePeriod::Yesterday will mean "today" on the Microsoft server for some accounts.

I'm getting the data through AccountPerformanceReport.

I've also tried setting ReportTimeZone but didn't make any difference unfortunately.

Below is the error:

>   ["previous":"Exception":private]=>
>   NULL
>   ["faultstring"]=>
>   string(70) "Invalid client data. Check the SOAP fault details for more information"
>   ["faultcode"]=>
>   string(8) "s:Server"
>   ["detail"]=>
>   object(stdClass)#191 (1) {
>     ["ApiFaultDetail"]=>
>     object(stdClass)#186 (3) {
>       ["TrackingId"]=>
>       string(36) "c5ae8196-3bc7-44a8-a659-89529c21456f"
>       ["BatchErrors"]=>
>       string(0) ""
>       ["OperationErrors"]=>
>       object(stdClass)#171 (1) {
>         ["OperationError"]=>
>         object(stdClass)#166 (4) {
>           ["Code"]=>
>           string(4) "2004"
>           ["Details"]=>
>           string(0) ""
>           ["ErrorCode"]=>
>           string(23) "NoCompleteDataAvaliable"
>           ["Message"]=>
>           string(232) "You requested a report with complete data for all included campaigns. Currently only partial data is available in the respective time zone of one or more campaigns. Please try again later or submit a report request for partial data."
>         }
>       }
>     }

**Comment by eric-urban** [comment]
@Smartsasse it sounds like you are trying to get complete data for accounts with different time zones. By definition the data will not be complete at the same time across [time zones](https://docs.microsoft.com/en-us/advertising/guides/reports?view=bingads-13#reptimezones). Have you tried splitting up the requests into batches of accounts that have the same time zone?

**Comment by Smartsasse** [comment]
Well I got it to work by setting "ReturnOnlyCompleteData" to false, but I'm not really sure what it means. According to the documentation I can't rely on that the data is correct or finished in any way. I wanna get data for the current month up to yesterday but as I said, for some accounts i get the same error as when i try to get data for an unfinished period like "today".

My guess is that it has with timezones to do but I've tried setting the timezone manually but it doesn't work either.

But I guess it might be safe enough to use with "ReturnOnlyCompleteData" set to false even though the documentation make it sound like it can't be trusted in any way.

https://docs.microsoft.com/en-us/advertising/reporting-service/reportrequest?view=bingads-13
"there is no indication as to whether the data is complete, and the report will contain only the data that the system has finished processing"

**Comment by eric-urban** [comment]
@Smartsasse the ReturnOnlyCompleteData flag is how you can be sure all data for the submitted time range is ready. Its not always appropriate or possible to wait for the end of a date range. For example some clients want running performance data for 'Today', even though today is by definition still in progress.

**Comment by Smartsasse** [comment]
Yes I understand that. But I should be able to get data for "Yesterday" with "ReturnOnlyCompleteData" set to "true". But that isn't possible, even if I try setting the timezone to some different values.

**Comment by eric-urban** [comment]
@Smartsasse in this case it will help to send [support](https://about.ads.microsoft.com/en-us/microsoft-advertising-support) the SOAP request and response with tracking ID and timestamp. Our team can check your specific accounts.
