### ISSUE TITLE
Incorrect data : CurrentMaxCpc

### ISSUE THREAD

**Issue by karismatic** [BingAds/BingAds-PHP-SDK#117]
Hi Guys,
I'm getting incorrect data from your API vs what is in the account.

Specifically I'm calling a KeywordPerformanceReportRequest
on the column : CurrentMaxCpc
with LastSevenDays

and the following columns 
              KeywordPerformanceReportColumn::CampaignName,
              KeywordPerformanceReportColumn::CampaignId,
              KeywordPerformanceReportColumn::AdGroupName,
              KeywordPerformanceReportColumn::Keyword,
              KeywordPerformanceReportColumn::Clicks,
              KeywordPerformanceReportColumn::Impressions,
              KeywordPerformanceReportColumn::Spend,
              KeywordPerformanceReportColumn::CurrentMaxCpc,
              KeywordPerformanceReportColumn::AverageCpc,
              KeywordPerformanceReportColumn::AveragePosition          

I'm getting outdated data (more than several days old) for CurrentMaxCpc.
The rest of the data is correct.
but we've made changes to the CPCs several days ago.

Bing account id : 3201442
API report requestId : 962373304740
don't have the exact timestamp sorry 
around 19/11/2019 13:00 CET

Example of outaded data 
(campaign / adgroup / keyword)

DMV - CA - Search / Drivers Test Questions / +drivers + test +questions
CurrentMaxCpc in the report > $0.5
current Bid in  Bing interface > $0.2

DMV - CA - Search / Drivers Test Questions / 2019 +california +drivers +test +questions
CurrentMaxCpc in the report > $0.5
current Bid in  Bing interface > $0.31

DMV - CA - Search / Drivers Test Questions / ca drivers test questions
CurrentMaxCpc in the report > $0.5
current Bid in  Bing interface > $0.36

thanks.

**Comment by eric-urban** [comment]
@karismatic please [contact our support team](https://about.ads.microsoft.com/en-us/microsoft-advertising-support) for a timely response to production data issues. 

Best regards,
Eric
