### ISSUE TITLE
Why version number in namespaces etc

### ISSUE THREAD

**Issue by madsem** [BingAds/BingAds-PHP-SDK#119]
Every time I work with this API I'm put off again by all the references to the current version in namespaces, constants and so forth. It might be a good idea to refactor this in the future so that the current version is always in the "root" directory without version numbers?

I think that would make it a lot easier to update code to a new API version, without having to sift through a million files? :)

Just an idea.

**Comment by eric-urban** [comment]
@madsem I recall the original intent was to allow multiple versions in the same package. We had heard feedback years ago via [.NET, Java, and Python SDKs](https://docs.microsoft.com/en-us/advertising/guides/client-libraries?view=bingads-13#namespaces) that clients require flexibility during migration to run multiple supported API versions side by side (even reference multiple versions in the same application file). Our PHP library followed the same pattern, and [other API SDKs](https://github.com/googleads/google-ads-php/tree/master/src/Google/Ads/GoogleAds) also follow this convention. I understand your point, and I hope this explanation helps. Thanks!
