### ISSUE TITLE
ApplyOfflineConversions functionality issue

### ISSUE THREAD

**Issue by Eyalevin** [BingAds/BingAds-PHP-SDK#120]
Hey,
I use ApplyOfflineConversions function from CampaignManagementExampleHelper class

PartialErrors returned an empty object,  and that means there were no errors during the run.

The issue appears to be in Campaign Management Dashboard,
We have waited for over than 5 hours to receive the data in Advertising Dashboard and noticed that fields such as 'Conversions', 'Revenue', 'Repeat rate' are empty,  which leads us to think the data was not sent properly.

BR,
Eyal Levin

**Comment by eric-urban** [comment]
@Eyalevin this does not appear to be an SDK issue. I suggest that you [contact support here](https://about.ads.microsoft.com/en-us/microsoft-advertising-support), and we'll be happy to investigate.
