### ISSUE TITLE
ReportDownloadUrl is publicly accessible

### ISSUE THREAD

**Issue by aknosis** [BingAds/BingAds-PHP-SDK#123]
The report download url generated via report request is a publicly accessible url. This data should not be available to any machine other than that which has requested the report...

To reproduce, follow the code from the example here: https://github.com/BingAds/BingAds-PHP-SDK/blob/master/samples/V13/ReportRequests.php and take the [ReportDownloadUrl](https://github.com/BingAds/BingAds-PHP-SDK/blob/master/samples/V13/ReportRequests.php#L106) and download the report from any machine in the world.

**Comment by eric-urban** [comment]
@aknosis since this is not specific to the PHP library, I suggest please submit a service feature request via [Microsoft Advertising Feature Suggestions](https://microsoftadvertising.uservoice.com/forums/82363-microsoft-advertising-feature-suggestions). Thanks!
