### ISSUE TITLE
WebAuthentication error

### ISSUE THREAD

**Issue by projectyang** [BingAds/BingAds-PHP-SDK#125]
Ran into PHP Fatal error: Class 'Microsoft\BingAds\Auth\OAuthWebAuthCodeGrant' not found. when trying to use the web authentication sample.

I believe it's the composer.json file that's causing it:

`    "autoload": {
        "psr-4": {
            "Microsoft\\BingAds\\": "/src/"
        }`

To get it working, I changed the file path to "src/" instead.

**Comment by eric-urban** [comment]
@projectyang thanks for raising this issue. We'll fix it in the next release.

**Comment by eric-urban** [comment]
@projectyang this should be fixed in version 13.0.4. Thanks!
