### ISSUE TITLE
How do I retrieve customer details, developer token and reports?

### ISSUE THREAD

**Issue by amitklahiri** [BingAds/BingAds-PHP-SDK#127]
Hi. 

After login I wish to retrieve the customer id and name related to the apps. How do I do retrieve the customer information? Can you please refer me the example from the sample folder? Any other examples will be appreciated. 

Where do I find the Developer token? Please refer me the menu options and / or URL. 

After successful with customer details, I wish to retrieve the customer's campaigns details. Also, the metrics such as Clicks, Spend, Impressions, Conversions, etc. need to be retrieved. What this metrics are called? Is this the performance reports? How do I retrieve these metrics values for a date range? Please refer some examples?

Regards,
Amit

**Comment by eric-urban** [comment]
@amitklahiri - 

Please see the [Get Started guide](https://docs.microsoft.com/en-us/advertising/guides/get-started?view=bingads-13#get-developer-token) for developer token info.  

Note, for quicker response times please feel free to post general API questions [here in the forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=BingAds). 

Thanks for your patience, and please let me know if you have any follow up questions.

Best regards,
Eric
