### ISSUE TITLE
Unable to load autoload.php within WebAuthHelper.php

### ISSUE THREAD

**Issue by olivasworker** [BingAds/BingAds-PHP-SDK#134]
Hi there! I was working on the bingads API integration in ours system, and I noticed that the path within vendor/microsoft/bingads/samples/WebAuthentication/WebAuthHelper.php for autoload is incorrect, being the autoload under vendor/microsoft/bingads/vendor/ path, how must the file autoload.php be loaded by WebAuthHelper.php (and the other files of the library) ? Which one is the correct path for the bingads autoload.php file ?

Thanks,
Jorge

**Comment by eric-urban** [comment]
@olivasworker the samples library target a console app. If you are referencing them from your web app, sure please update the path as needed. The web app as written works for me still. Either way it sounds like you found a way to make it work in your dev environment. Thanks!
