### ISSUE TITLE
Incorrect key for keep_alive setting when creating new instances of SoapClient

### ISSUE THREAD

**Issue by 20TRIES** [BingAds/BingAds-PHP-SDK#137]
```
// Disable keep-alive to avoid 'Process open FD table is full'
'keep-alive' => FALSE,
```

should be:

```
// Disable keep-alive to avoid 'Process open FD table is full'
'keep_alive' => FALSE,
```

Having a quite a few issues with reaching the maximum open files using the current version until we changed the hyphen to an underscore.

See https://github.com/BingAds/BingAds-PHP-SDK/blob/main/src/Auth/ServiceClient.php#L242

**Comment by Victor-emil** [comment]
I think I might be experiencing some of the same issues. Specifically I get exceptions like 
`SoapFault exception: [HTTP] Error Fetching http headers` and `failed to open stream: Too many open files`.
