### ISSUE TITLE
adPerformaceReport report returns empty Headlines for RSA

### ISSUE THREAD

**Issue by eng-samy** [BingAds/BingAds-PHP-SDK#142]
After download adPerformaceReport, Headline and LongHeadline are empty for all Responsive Search Ads.
![image](https://user-images.githubusercontent.com/10207235/100127304-42b7d400-2e7f-11eb-93f6-1dd6c89110f0.png)

**Comment by eric-urban** [comment]
@eng-samy those report columns are not supported for responsive search ads via the API. I can double check if asset level reporting is on the API roadmap, and either way we will update the documentation to clarify. 

You can get asset level reporting via the Microsoft Advertising UI. Please see the section on _Using reports to track responsive search ads_ in the [About responsive search ads](https://help.ads-int.microsoft.com/#apex/ads/en/60037/0-500) help page.
