### ISSUE TITLE
Provide a mechanism that allows to pass custom options to SoapClient

### ISSUE THREAD

**Issue by juanparati** [BingAds/BingAds-PHP-SDK#146]
In the [AuthHelper sample](https://github.com/BingAds/BingAds-PHP-SDK/blob/3f734c384c51aa22bb85a716951eb07f5cdfa897/samples/V13/AuthHelper.php), there some "ini_set" sentences that will modify the global behavior of the SoapClient.

It's a bad practice to set global configuration in runtime because it can pollute the behavior of other SoapClient instances that are not related to BingAds.

A solution to this problem it could be allow to provide a method that allow to pass custom options to the SoapClient, so it could be possible to modify the cache options directly on the SoapClient instance used by BingAds.

See [SoapClient options](https://www.php.net/manual/en/soapclient.construct.php) for more details.

**Comment by leongersen** [comment]
I'd like to chime in to this; as of March 8th, we're seeing a large number of connection timeouts while attempting to call the API. There isn't currently an accessible way to set the `connection_timeout` option when constructing the `\SoapClient`.

```SoapClient::__doRequest(): connect() failed: Connection timed out```

**Comment by eric-urban** [comment]
@juanparati and @leongersen - We will take this up as a priority: "allow to pass custom options to the SoapClient". The AuthHelper sample might remain unmodified since its an example and your application shouldn't have any dependencies on it.

**Comment by eric-urban** [comment]
@juanparati and @leongersen - Wanted to provide an update that we are actively working on this feature request. We'll follow up again.

**Comment by eric-urban** [comment]
@juanparati and @leongersen - The [options ](https://github.com/BingAds/BingAds-PHP-SDK/blob/main/src/Auth/ServiceClient.php#L87)are available with release 13.0.9. Please reach out with any follow up questions.

**Comment by leongersen** [comment]
I noticed this was in the latest release, thanks!
