### ISSUE TITLE
Fault String: SOAP-ERROR: Parsing WSDL: Couldn't load from 

### ISSUE THREAD

**Issue by adrianlaraperez88** [BingAds/BingAds-PHP-SDK#147]
Hi M Ads. Team, I use this API for around 1 or 2 years and the first time sees this issue, I have this error pull the Stats report or get Accounts info.
`-----
Fault Code: WSDL
Fault String: SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://clientcenter
.api.bingads.microsoft.com/Api/CustomerManagement/v13/CustomerManagementService.
svc?singleWsdl' : failed to load external entity "https://clientcenter.api.binga
ds.microsoft.com/Api/CustomerManagement/v13/CustomerManagementService.svc?single
Wsdl"

Fault Detail:
NULL
-----
`
PHP Version : PHP 7.2.34 
SDK version:13.0.8

![image](https://user-images.githubusercontent.com/19626181/114243386-74c36180-995a-11eb-814b-fa237123cea9.png)

**Comment by mihail-finsbury-bg** [comment]
I'm facing the same issue as well. This issue seems to appear on some random basis. Start the same script twice may result in either successful report generation and download or the error shown above. 

I'm running on PHP 8.0.3 and SDK version 13.0.8, but I doubt that the issue has anything to do with the PHP version.

**Comment by eric-urban** [comment]
@adrianlaraperez88 and @mihail-finsbury-bg this issue should now be resolved. Please reopen if you observe otherwise. Thanks!

**Comment by adrianlaraperez88** [comment]
@eric-urban ty so much i will check again

**Comment by mihail-finsbury-bg** [comment]
@eric-urban issue seems to be fix. Thanks a lot.

**Comment by adrianlaraperez88** [comment]
@eric-urban All those days working fine but today have the same issue 
`No report data for the submitted request.
-----
Fault Code: WSDL
Fault String: SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://clientcenter
.api.bingads.microsoft.com/Api/CustomerManagement/v13/CustomerManagementService.
svc?singleWsdl' : `

**Comment by mihailgoosbg** [comment]
Yes indeed issue seems to be back. There is concrete pattern, it just fails on some random order. One day 7 reports that we download can all go trough and the next day 2 or 3 of them may fail with the error message stated above.

**Comment by adrianlaraperez88** [comment]
I Have an issue with Year Report and some Day Reports (random) days. This affect dashboards and client Report

**Comment by adrianlaraperez88** [comment]
Any Updates about this issue ?

**Comment by adrianlaraperez88** [comment]
Any Update?

**Comment by adrianlaraperez88** [comment]
Hi, @eric-urban continue with this error random, any update?
