### ISSUE TITLE
Destination URL Performance Report Issues

### ISSUE THREAD

**Issue by mihailgoosbg** [BingAds/BingAds-PHP-SDK#154]
Some of the columns in the destination URL performance report appears to be blank/empty when they are expected to have values. In particular I'm referring to the "Destination URL" and "Final URL Suffix" columns.

On the account level I've configured final URL suffix. Just for the record result is the same even if I configure final URL suffix on campaign level.
![Screenshot (1)](https://user-images.githubusercontent.com/8723559/122369332-c42f9a80-cf66-11eb-9447-d214c413c7f0.png)

When I download the destination URL report it looks like this:
[138979227126-1.csv](https://github.com/BingAds/BingAds-PHP-SDK/files/6669023/138979227126-1.csv)

"Destination URL" and "Final URL Suffix" columns are empty when it is not supposed to be the case according to the API report columns documentation.
https://docs.microsoft.com/en-us/advertising/reporting-service/destinationurlperformancereportcolumn?view=bingads-13

I'm on the latest version of the PHP API (v 0.13.0.10) and I'm using PHP 8.0

**Comment by qitia** [comment]
I asked the feature team, and here is the answer:

_Final URL has replaced Destination URL in reports. Destination URL was supposed to be deprecated. Given we haven’t release API V14 where we could have removed this column, we carry this column and return empty string.
Customer has only 1 Ad – 82188748539888 which has final URL suffix and that Ad didn’t serve on 6/16, so final URL suffix is empty string._
