### ISSUE TITLE
Can't reliably get deleted items, exceptions thrown when trying to modify a deleted item.

### ISSUE THREAD

**Issue by madsem** [BingAds/BingAds-PHP-SDK#157]
Hi,

I don't understand how one is supposed to sync deleted entities via API?
Because the GET services do not return a `deleted` status, the performance reports are unreliable at best.
I have an adgroup performance report, it shows ad groups as `active`, but the entire campaign was deleted (It also had impressions).

But then when you try to modify `deleted` items, the Microsoft ads client throws exceptions (Which in turn cannot really be handled because I can't tell which items are deleted, so these exceptions just clutter my sentry logs).

Am I being too blind to see something obvious, or is the above really how this works and there's nothing I can do about it?

**Comment by qitia** [comment]
I asked the feature team and here is the answer:

_Reporting API doesn’t cascade down parent entity deletion status to its child. Customer deleted campaign, so campaign status will be deleted, not ad groups, keywords, ads/ etc. underneath that campaign.
Customer can fetch campaign status too along with ad group status and combine it their side._
