### ISSUE TITLE
Weird exceprion from service client

### ISSUE THREAD

**Issue by vovan47** [BingAds/BingAds-PHP-SDK#16]
Hi, @eric-urban!

Somehow I got a weird exception logged from line 265 of ServiceClient.php
It had no message and trace is ending with:
```
#0 .../library/vendor/microsoft/bingads/src/Auth/ServiceClient.php(265): SoapClient->SoapClient('https://clientc...', Array)

#1 .../library/vendor/microsoft/bingads/src/Auth/ServiceClient.php(195): Microsoft\BingAds\Auth\ServiceClient->RefreshServiceProxy()

#2 .../library/vendor/microsoft/bingads/src/Auth/ServiceClient.php(125): Microsoft\BingAds\Auth\ServiceClient->SetAuthorizationData(Object(Microsoft\BingAds\Auth\AuthorizationData))
```

How is that possible, considering that this line has error suppression in it?
And can you put some lights on why the error suppression is needed here?

Thanks,
Vladimir.

**Comment by eric-urban** [comment]
Hi, @vovan47 -
Will you please add more details about the repro steps and more complete error trace?
Best regards,
Eric

**Comment by eric-urban** [comment]
Closing as no repro
