### ISSUE TITLE
Reporting API slowdown: often fails to connect

### ISSUE THREAD

**Issue by leongersen** [BingAds/BingAds-PHP-SDK#161]
I'm seeing a slowdown on the reporting API as of ~ 2021-12-02 17:00 UTC. DNS resolution and TCP connect are fast, but the SSL handshake with `reporting.api.bingads.microsoft.com:443` is very slow and often times out or fails.

Depending on when the timeout happens, this may present as one of the following errors/warnings:

```
SoapClient::__doRequest(): SSL: Connection reset by peer
Error Fetching http headers
SoapClient::__doRequest(): SSL: Handshake timed out
SoapClient::__doRequest(): Failed to enable crypto
SoapClient::__doRequest(): connect() failed: Connection timed out

```

This was also reported by someone else for the Python SDK: https://github.com/BingAds/BingAds-Python-SDK/issues/196

**Comment by qitia** [comment]
per this: https://github.com/BingAds/BingAds-Python-SDK/issues/196, it is working fine now.
