### ISSUE TITLE
composer require microsoft/bingads not working

### ISSUE THREAD

**Issue by umair1191** [BingAds/BingAds-PHP-SDK#17]
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - The requested package microsoft/bingads No version set (parsed as 1.0.0) is satisfiable by microsoft/bingads[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

composer.json:
{
    "name": "microsoft/bingads",
    "description": "This project provides a set of PHP client libraries that make it easy to access Bing Ads service APIs.",
    "keywords": [ "php", "bingads", "bing ads", "sdk" ],
    "license": "Apache-2.0",
    "type": "library",
    "homepage": "https://github.com/BingAds/BingAds-PHP-SDK",
    "require": {
        "php": ">=5.5",
        "ext-curl": "*",
        "ext-openssl": "*",
        "ext-soap": "*"
    },
    "require-dev": {
        "ext-curl": "*",
        "ext-openssl": "*",
        "ext-soap": "*"
    },
    "autoload": {
        "psr-4": {
            "Microsoft\\BingAds\\": "/src/"
        }
    },
    "authors": [
        {
            "name": "Microsoft",
            "homepage": "https://github.com/BingAds/BingAds-PHP-SDK/graphs/contributors"
        }
    ]
}

**Comment by J7mbo** [comment]
https://getcomposer.org/doc/04-schema.md#minimum-stability

and

https://getcomposer.org/doc/04-schema.md#package-links

**Comment by umair1191** [comment]
Thanks J7mbo, 
Can you verify what is wrong with my composer.json file? I have written above.

**Comment by umair1191** [comment]
oh got it, I have just removed first line "name": "microsoft/bingads"  from composer.json and it worked.
