### ISSUE TITLE
Where did SearchAccountsRequest go?

### ISSUE THREAD

**Issue by lezhnev74** [BingAds/BingAds-PHP-SDK#177]
I don't see that in changelog, why did that and many other classes disappear?
The used to be in `Microsoft\BingAds\V13\CustomerManagement` namespace  (see `samples/V13/CustomerManagementExampleHelper.php` for example).

**Comment by austinkregel** [comment]
This would be related to the latest release 13.0.15, if you lock your version at 13.0.14 you should still be able to access these classes.

This is related to #176

**Comment by qitia** [comment]
We just released a new version 13.0.15.1. Sorry for any inconvenience that brought by version 13.0.15 and late response.

Let me know if you still see any issue.
