### ISSUE TITLE
Issue with ServiceClient class in latest 13.0.15.1 release

### ISSUE THREAD

**Issue by JamieTFLI** [BingAds/BingAds-PHP-SDK#179]
After receiving the following error:
`PHP Fatal error:  Uncaught Error: Class "Microsoft\BingAds\Auth\ServiceClient" not found`

I looked at the changes between 13.0.15 and 13.0.15.1 and noticed the class PHP tag appear to be broken.
![image](https://user-images.githubusercontent.com/122042111/210833621-d0c61f4e-0423-46ed-a20d-836ea5e1f35e.png)

https://github.com/BingAds/BingAds-PHP-SDK/compare/v13.0.15...v13.0.15.1

**Comment by qitia** [comment]
My bad. push 13.0.15.2 to fix.
