### ISSUE TITLE
How to get the report of all the ad groups of a campaign

### ISSUE THREAD

**Issue by elegos** [BingAds/BingAds-PHP-SDK#23]
Hello!

I'm trying to find out in the Bing Ads API docs which call (and how to configure it) in order to get the report of all the ad groups of a campaign for the given period of time.

May you please link me to the relative doc, or to create an example for me?

Thanks.

**Comment by eric-urban** [comment]
Hello @elegos -  

Which report type are you interested in using e.g. here is an example for [KeywordPerformanceReportRequest](https://github.com/BingAds/BingAds-PHP-SDK/blob/master/samples/V11/ReportRequests.php#L87). The sample will download data for all campaigns in the account. 

If you only want a specific campaign, set the corresponding scope e.g. the following changes to the [GetKeywordPerformanceReportRequest ](https://github.com/BingAds/BingAds-PHP-SDK/blob/master/samples/V11/ReportingHelper.php#L62) example function:

```php
$report->Scope = new AccountThroughAdGroupReportScope();
$report->Scope->AccountIds = null;
$report->Scope->AdGroups = null;
$scopes = array();
$campaignReportScope = new CampaignReportScope();
$campaignReportScope->AccountId = $accountId;
$campaignReportScope->CampaignId = CampaignIdGoesHere;
$scopes[] = $campaignReportScope;
$report->Scope->Campaigns = $scopes;
```

I hope this helps!

Also note that we are actively monitoring the [Bing Ads API Development forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=BingAds) in case you have any other Bing Ads API questions. 

Best regards,
Eric

**Comment by elegos** [comment]
Thanks Eric :+1:
