### ISSUE TITLE
Can't get GetKeywordIdeas to work

### ISSUE THREAD

**Issue by Spiritvoin** [BingAds/BingAds-PHP-SDK#26]
I'm trying to implement GetKeywordIdeas service but SearchParameters are not fulfilled by some reason.
Here is a part of my PHP code:

    
    $GLOBALS["Proxy"] = $GLOBALS["AdInsightProxy"];
    $searchParameter = new QuerySearchParameter();
    $searchParameter->Queries = ["tatoo", "body"];
    $searchParameters[] = $searchParameter;$request = new GetKeywordIdeasRequest();
    $request->ExpandIdeas = true;
    $request->SearchParameters = $searchParameters;

    $GLOBALS['Proxy']->GetService()->GetKeywordIdeas($request);`
Then GetKeywordIdeas action formes the following XML:

`  <?xml version="1.0" encoding="UTF-8"?>
  <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
                   xmlns:ns1="Microsoft.Advertiser.AdInsight.Api.Service.V11"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns:ns2="http://schemas.datacontract.org/2004/07/Microsoft.BingAds.Advertiser.AdInsight.Api.DataContract.V11.Entity.SearchParameters">
      <SOAP-ENV:Header>
          <ns1:CustomerAccountId>AccountIdGoesHere</ns1:CustomerAccountId>
          <ns1:CustomerId>CustomerIdGoesHere</ns1:CustomerId>
          <ns1:DeveloperToken>DeveloperTokenGoesHere</ns1:DeveloperToken>
          <ns1:UserName/>
          <ns1:Password/>
          <ns1:AuthenticationToken>
              OAuthAccessTokenGoesHere
          </ns1:AuthenticationToken>
      </SOAP-ENV:Header>
      <SOAP-ENV:Body>
          <ns1:GetKeywordIdeasRequest>
              <ns1:ExpandIdeas>true</ns1:ExpandIdeas>
              <ns1:IdeaAttributes xsi:nil="true"/>
              <ns1:SearchParameters>
                  <ns2:SearchParameter/>
              </ns1:SearchParameters>
          </ns1:GetKeywordIdeasRequest>
      </SOAP-ENV:Body>
  </SOAP-ENV:Envelope>`

And we could see that SearchParameter is still empty but it should be fulfilled. And this issue I have with all the Parameters that I`m trying to set (some of them are below):

DateRangeSearchParameter 
LanguageSearchParameter  
NetworkSearchParameter 
LocationSearchParameter

After the request I got the following issue:

"The server was unable to process the request due to an internal error. For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the "servicedebug" configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs."

Any help is appreciated, thanks!

**Comment by eric-urban** [comment]
Thanks for the request, and we've added a new [KeywordPlanner](https://github.com/BingAds/BingAds-PHP-SDK/blob/master/samples/V11/KeywordPlanner.php) sample. I hope this helps!
