### ISSUE TITLE
FatalErrorException in CampaignManagementHelper.php line 83: syntax error, unexpected '.', expecting ',' or ';'

### ISSUE THREAD

**Issue by asmagillani** [BingAds/BingAds-PHP-SDK#32]
Hi,

I am getting this error for PHP 7 , but its working fine in case of php 5.6 

Thanks

**Comment by swordbeta** [comment]
I think you mean the other way around? Shouldn't work in <= PHP 7. Class constant string concatenation was introduced in PHP 7.

I'm not sure why you would want to use the CampaignManagementHelper though which is riddled with global variables, it's only meant as an example.

**Comment by eric-urban** [comment]
@asmagillani and @swordbeta please let us know how could CampaignManagementHelper be more useful? @swordbeta is correct this is only an example, but please let us know any suggestions.

**Comment by eric-urban** [comment]
Please feel free to open a new issue with more details.
