### ISSUE TITLE
KeepAlive option for SoapClient - Process open FD table is full 

### ISSUE THREAD

**Issue by Mischosch** [BingAds/BingAds-PHP-SDK#39]
Hey there,

running `BingAds-PHP-SDK` with CentOS and PHP 7.1 I get `Process open FD table is full ` curl exceptions for running `ApplyOfflineConversionsRequest` inside a loop.

Adding `keep_alive` option with `false` value to SoapClient init inside https://github.com/BingAds/BingAds-PHP-SDK/blob/master/src/Auth/ServiceClient.php#L218-L235 - and problem is gone.

So - I could open a PR for adding `keep_alive` with `false` setting - or is this something that should be configurable from outside? We would need to add another param to `ServiceClient` constructor then.

I can provide the needed changes within a PR - just wanted to ask before, if there are any opinions/objections on that topic from your side.

And for the fun part of this story: Google AdWords does have same problems:  https://groups.google.com/forum/#!topic/adwords-api/WusAoMOJy_A

Would be great to get a fix for it into upstream instead of having to monkey patch this.

Kind Regards

**Comment by Mischosch** [comment]
(see https://github.com/googleads/googleads-php-lib/pull/301)

**Comment by eric-urban** [comment]
@Mischosch thanks for the great suggestion. Unless any objections are raised soon, we will plan to set keep-alive false in the next release. As you mentioned we should also allow options to be set in the ServiceClient constructor.

**Comment by eric-urban** [comment]
@Mischosch this issue of FD table full is resolved via version 11.5.7. We set keep-alive false internally. Whether to implement a new constructor that accepts $options will be taken up separately. Thanks again!

**Comment by Mischosch** [comment]
Great, thanks a lot - much appreciated! 🙇
