### ISSUE TITLE
Why not, separate authentication?

### ISSUE THREAD

**Issue by josedacosta** [BingAds/BingAds-PHP-SDK#4]
Hello,

Why not, separate authentication?
This allows: a customization of the login (modification of the scope), and call the profile, ...

Https://github.com/BingAds/BingAds-PHP-SDK/blob/v0.10.4/src/Auth/LiveComOAuthService.php#L97

Example in Google Ads:
Https://packagist.org/packages/google/auth
Https://packagist.org/packages/googleads/googleads-php-lib

Thank you

**Comment by eric-urban** [comment]
For Bing Ads SDKs (including PHP, .NET, Java, Python) there are some dependencies e.g., the scope must be bingads.manage to use AuthorizationData via ServiceClient. The OAuth classes in Bing Ads SDKs are specifically designed to allow the supported scopes and auth grant flows that Bing Ads supports i.e., do not support other scopes outside of Bing Ads.
