### ISSUE TITLE
Remove trailing  ?>

### ISSUE THREAD

**Issue by hackzilla** [BingAds/BingAds-PHP-SDK#40]
The trailing ?> is unnecessary in pure php files.
There is a chance there could be whitespace after them.

**Comment by eric-urban** [comment]
@hackzilla great feedback, thanks! We have not been consistent e.g., '?>' is used [here](https://github.com/BingAds/BingAds-PHP-SDK/blob/master/src/Auth/ApiEnvironment.php) and [here](https://github.com/BingAds/BingAds-PHP-SDK/blob/master/samples/AuthHelper.php), but not [here](https://github.com/BingAds/BingAds-PHP-SDK/blob/master/src/V11/AdInsight/AdApiError.php). We will address it in the next release.

**Comment by hackzilla** [comment]
I'm over the moon that I can install the SDK with composer 👍

**Comment by eric-urban** [comment]
@hackzilla this issue is resolved via version 11.5.7. Thanks again!
