### ISSUE TITLE
How to set aggregator role? (live or sandbox)

### ISSUE THREAD

**Issue by spatariu** [BingAds/BingAds-PHP-SDK#42]

**Comment by eric-urban** [comment]
@spatariu please contact your account manager for aggregator credentials whether production or sandbox. If you are not currently a reseller but would like to become one, go to the [The Bing Partner Program](https://advertise.bingads.microsoft.com/en-us/bing-partners/welcome) welcome page. I hope this helps!

**Comment by spatariu** [comment]
Thanks for the quick reply, we just made a request for an agency token, I guess there will be an aggregator role user.

**Comment by spatariu** [comment]
Hi, can a sandbox user be assigned an aggregator role? I try to run the CustomerSignup example but I got the missing 33 aggregator role error. Thanks!

**Comment by eric-urban** [comment]
@spatariu Yes. Please contact your account manager for aggregator credentials whether production or sandbox. If you are not currently a reseller but would like to become one, go to the [The Bing Partner Program](https://advertise.bingads.microsoft.com/en-us/bing-partners/welcome) welcome page.
