### ISSUE TITLE
Need to revert PHP7 coalesce operators to be PHP 5.6.* compatible

### ISSUE THREAD

**Issue by look234** [BingAds/BingAds-PHP-SDK#43]
Found two PHP 7 coalesce operators in the sample code. The documentation here, https://docs.microsoft.com/en-us/bingads/guides/get-started-php, states that the PHP version of the Bing Ads API should be PHP 5.6.30 compatible. We need to revert them to be compatible with the older versions for now.

Here:
https://github.com/BingAds/BingAds-PHP-SDK/blob/5eb85a584e8c0c6a9f309e99cc5ff79819f8e5da/samples/V11/CampaignManagementHelper.php#L1588

And here:
https://github.com/BingAds/BingAds-PHP-SDK/blob/5eb85a584e8c0c6a9f309e99cc5ff79819f8e5da/samples/V11/CampaignManagementHelper.php#L1621

**Comment by eric-urban** [comment]
@look234 thanks for catching these. We will update the sample.

**Comment by look234** [comment]
@eric-urban Thank you!

**Comment by eric-urban** [comment]
@look234 this issue is resolved via version 11.5.7. Thanks again!
