### ISSUE TITLE
Auction Insight API miss "OutrankingShare" Field

### ISSUE THREAD

**Issue by jackzing** [BingAds/BingAds-PHP-SDK#45]
Hello,
 I can see the "OutrankingShare" field from the web UI but I can't get this filed when I use bing ads API and the field "OutrankingShare" is not also in AuctionInsightKPINode.php, so is this a bug?

**Comment by eric-urban** [comment]
@jackzing the auction insights are not [documented](https://docs.microsoft.com/en-us/bingads/ad-insight-service/ad-insight-service-reference) and therefore not officially supported. Anything marked '[Reserved](https://github.com/BingAds/BingAds-PHP-SDK/blob/master/src/V11/AdInsight/AuctionInsightKPINode.php#L9)' is not supported, or only supported for internal use. The team is currently discussing whether to open up Auction insights in API V12, so I'll share this feature request i.e., to include Outranking Share. Thanks!

**Comment by jackzing** [comment]
@eric-urban 

OK, got it. Thank you!
