### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by braankoo** [BingAds/BingAds-PHP-SDK#49]
Hi,
when I want to download all adGroups within my campaigns i'm experiencing one problem.

```
public function getAdGroups($campaignId)
    {
        $request = new GetAdGroupsByCampaignIdRequest();
        $request->CampaignId = $campaignId;
       // return $this->getProxy()->GetService()->GetAdGroupsByCampaignId($request);
    }
```
When I loop thru all campaigns and just authorize (without getting adgroup details), its all good.
But when i uncomment return, its really consuming a of lot memory.

Now Im not sure where problem is. 

You have some idea ?

**Comment by eric-urban** [comment]
@braankoo I am not able to reproduce any significant memory loss. Please feel free to reopen this issue with your repro details e.g., memory used vs expected, etc. Thank you.
