### ISSUE TITLE
HttpService: Params with cURL are not encoded

### ISSUE THREAD

**Issue by blurayne** [BingAds/BingAds-PHP-SDK#51]
We had a problem with the client_secret which could be traced down to 

Microsoft\BingAds\Auth\HttpService:
```
- $query = $query . $key . '=' . $val;
+ $query = $query . $key . '=' . rawurlencode($val);
```

We worked around by simply generating a client_secret without "?%" characters. But this needs to be fixed.

**Comment by eric-urban** [comment]
@blurayne thanks for reporting this issue! Merged [here](https://github.com/BingAds/BingAds-PHP-SDK/commit/0d7d5e80e46b0b75ceca7cd10d7bdb2fa0eb02c2).
