### ISSUE TITLE
BulkUpload CSV Encoding Problem

### ISSUE THREAD

**Issue by J7mbo** [BingAds/BingAds-PHP-SDK#53]
We're uploading a Bulk CSV file, we've added a UTF-8 BOM. The contents of the CSV file look to be in the correct encoding.

When Bing has finished processing the file and we refresh the Campaigns page, the encoding is all wrong and the characters look wrong.

Is there something we need to explicitly set, apart from the UTF-8 BOM?

**Comment by eric-urban** [comment]
@J7mbo have you checked the contents of the Bulk upload result file? Do you have an example of the contents that are not expected (look wrong), and ideally a RequestId + timestamp? 

BTW for general API questions please feel free to post in the [API Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=BingAds).
