### ISSUE TITLE
Question XXXReportFilter

### ISSUE THREAD

**Issue by madsem** [BingAds/BingAds-PHP-SDK#56]
Hi,

I'm trying to filter reports I download to only include keywords with conversions, to make the report size smaller and easier to handle.

How would I go about that, looking at ConversionPerformanceReportFilter for example it doesn't seem to be possible, but I thought I'd better ask :)

Thank you!

**Comment by eric-urban** [comment]
@madsem such a filter is not currently supported. As always we encourage feature requests for UI and API via the [Bing Ads Feature Suggestions Forum](https://bingads.uservoice.com/forums/82363-bing-ads-feature-suggestions). 

Best regards,
Eric
