### ISSUE TITLE
php version reqs

### ISSUE THREAD

**Issue by odefini** [BingAds/BingAds-PHP-SDK#58]
All versions show php >=5.5 needed in packagist, however, after v0.11.5.8 the file Auth/LiveComOAuthService.php (at least) is using constant arrays which were introduced in php 5.6

**Comment by eric-urban** [comment]
@odefini good catch and we will update the requirements to >=5.6.

**Comment by eric-urban** [comment]
@odefini this has been updated in v11.12.1
