### ISSUE TITLE
Configuration not in constant in AuthHelper

### ISSUE THREAD

**Issue by ynizon** [BingAds/BingAds-PHP-SDK#61]
Hello,
We can't extend the AuthHelper class, and you have put api key and other config informations into this.
All websites have config file and coding the settings into this file is not recommanded.

We need to extend this class.
Please remove final, and replace const settings by protected.
Then in the function AuthenticateWithOAuth
you should replace AuthHelper::ClientId by $this->ClientId...

Thanks

**Comment by eric-urban** [comment]
@ynizon AuthHelper is a sample helper file, is not recommended for use in production, and was not meant to be extensible. You are welcome to use it as a starter and customize it as needed.
