### ISSUE TITLE
PHP Strict standards notice

### ISSUE THREAD

**Issue by Wenomer** [BingAds/BingAds-PHP-SDK#62]
Hey guys, i noticed the E_STRICT level notice in v12 classes, when i try to use `new OAuthDesktopMobileAuthCodeGrant()` class on `5.6.33` PHP version

`PHP Strict standards:  Static function Microsoft\BingAds\Auth\IOAuthService::getRedirectUrl() should not be abstract in /vendor/microsoft/bingads/src/Auth/IOAuthService.php on line 16`

looks like it is fixed in `7.0` but for now `5.6` it requirement for me, temporary i suppress the notice,but it little bit awkward, do you think it is possible to fix this notice in v12 classes?

Thanks!

**Comment by eric-urban** [comment]
@Wenomer thanks for the heads up! The [update](https://github.com/BingAds/BingAds-PHP-SDK/pull/63/commits/dcd13d99403042f2b824a61da1728ffe50e8cdf2) is merged and will be included in the next release e.g., next week.
