### ISSUE TITLE
The include and require path begin with a /

### ISSUE THREAD

**Issue by RoyBellingan** [BingAds/BingAds-PHP-SDK#71]
In almost all files 

require_once "/../vendor/autoload.php";
include "/AuthHelper.php";
include "/OutputHelper.php";
include "/CampaignManagementExampleHelper.php";

Those are from SearchUserAccounts.php

As per the specification in
   http://php.net/manual/en/function.include.php
If a path is defined — whether absolute (starting with a drive letter or \ on Windows, or / on Unix/Linux systems) or relative to the current directory (starting with . or ..) — the include_path will be ignored altogether. For example, if a filename begins with ../, the parser will look in the parent directory to find the requested file. 

Maybe you where willing to do http://php.net/manual/en/ini.core.php#ini.include-path

Using a . in the include path allows for relative includes as it means the current directory. However, it is more efficient to explicitly use include './file' than having PHP always check the current directory for every include. 

BTW the fix is just

find . -type f -exec sed -i 's/include "\//include ".\//g' {} +
find . -type f -exec sed -i 's/require_once "\//require_once ".\//g' {} +

If you want I can open a push request...

**Comment by RoyBellingan** [comment]
P.s. I forget to say that at least in linux the SDK in not working due to the initial / , so the interpreter try to find the file in root directory (and of course fails)

**Comment by eric-urban** [comment]
@RoyBellingan this is great feedback thanks! Would ```_DIR_``` work for you instead?

```php
require_once __DIR__ . "/../vendor/autoload.php";
require_once __DIR__ . "/CustomerManagementExampleHelper.php";
include __DIR__ . "/AuthHelper.php";
include __DIR__ . "/CampaignManagementExampleHelper.php";
```

**Comment by RoyBellingan** [comment]
Uhm I think is the same thing... having the . or the __DIR__ 

 Using a . in the include path allows for relative includes as it means the current directory.

**Comment by eric-urban** [comment]
@RoyBellingan we've updated the samples with DIR in the [latest release](https://github.com/BingAds/BingAds-PHP-SDK/releases/tag/v0.11.12.5). Thanks again for the feedback!
