### ISSUE TITLE
how to create refresh.txt

### ISSUE THREAD

**Issue by gouravempower** [BingAds/BingAds-PHP-SDK#73]
i am using this SDK and get this error 

> Error: invalid_grant Description: The provided value for the input parameter 'refresh_token' or 'assertion' is not valid.

how to create **refresh.txt** or where can i find this please help.. and thank u in advance for your help

**Comment by eric-urban** [comment]
@gouravempower I suggest starting with [this walkthrough example](https://docs.microsoft.com/en-us/bingads/guides/walkthrough-desktop-application-php?view=bingads-12). If you still observe the error then please [contact support](http://go.microsoft.com/fwlink/?LinkId=269631) or post a question with more details in the [developer forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=BingAds). 

I hope this helps!
