### ISSUE TITLE
be able to resume a report request

### ISSUE THREAD

**Issue by pentium10** [BingAds/BingAds-PHP-SDK#79]
Code in samples often terminates with the below message:

> The request is taking longer than expected.
> Save the report ID (***) and try again later

Could you please add a sample php script that will take the Report ID and resume the download

**Comment by eric-urban** [comment]
@pentium10 you can modify the provided sample i.e., remove the SubmitGenerateReport operation and insert your previous report request ID [here](https://github.com/BingAds/BingAds-PHP-SDK/blob/master/samples/V12/ReportRequests.php#L71). I hope this helps!
