### ISSUE TITLE
Namespace paths not resolving - Composer not installing

### ISSUE THREAD

**Issue by emedrado** [BingAds/BingAds-PHP-SDK#81]
I am experiencing a hard to time to run the composer require on this, I get an error stating "The requested package microsoft/bingads No version set (parsed as 1.0.0) is satisfiable by microsoft/bingads[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability." 

Tried to solve this with the Bing support, no luck.

If I ran composer install only I get a successful install, but when I try to run the OAuth2Callback.php i get the error  PHP Fatal error:  Class 'Microsoft\BingAds\Auth\OAuthWebAuthCodeGrant' not found in /home/adminlvorg/public_html/cronjob/bingads/BingAds-PHP-SDK-master/Oauth2Callback.php on line 25

**Comment by eric-urban** [comment]
@emedrado a similar issue was previously reported [here](https://github.com/BingAds/BingAds-PHP-SDK/issues/17). You might try to update [minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) to ```dev```. Does this help?
