### ISSUE TITLE
ArgumentNullException is not defined

### ISSUE THREAD

**Issue by vovan47** [BingAds/BingAds-PHP-SDK#9]
Hi Eric,

In the file `BingAds-PHP-SDK/src/Auth/OAuthWithAuthorizationCode.php` there is an `ArgumentNullException` being thrown in some cases. But I can't find it anywhere in this repository. Am I missing something?

Vladimir.

**Comment by J7mbo** [comment]
I just got this exact issue. Also I find I'm basically wrapping _everything_ they provide in an anti-corruption layer. Will submit a PR to fix...

**Comment by vovan47** [comment]
Do you think Eric is going to deploy it? He's not very active on the issues here :stuck_out_tongue:

**Comment by J7mbo** [comment]
@vovan47 I'm sure he's just busy, but he has just done a 'July refresh'. 

@eric-urban can you comment when you have a sec? This is listed as an official repo which I'm guessing you're working with on a day-to-day basis for your job now, need a hand with anything?

**Comment by eric-urban** [comment]
@vovan47 and @J7mbo thanks so much for raising this issue! (Wow I need to revisit the notifications from this repo ASAP as I had not seen notifications until today's '@' mention. ) 

For the short term this [update](https://github.com/BingAds/BingAds-PHP-SDK/commit/98a882f153a1b32e3f4db662ec438822bbdb9bdc) uses the general Exception. Long term we can revisit when to use more specific exceptions e.g. InvalidArgumentException.
