### ISSUE TITLE
REQUEST: GetAdGroupsByAccountId()

### ISSUE THREAD

**Issue by timothymarois** [BingAds/BingAds-PHP-SDK#92]
Currently, this does not exist. You can get all the campaigns by the account, but it doesn't allow you to get all the ad groups by the account. 

For consistency, should have `GetAdGroupsByAccountId()` just like we have `GetCampaignsByAccountId()`

**Comment by eric-urban** [comment]
@timothymarois to get all ad groups in an account, we recommend [Bulk download](https://docs.microsoft.com/en-us/bingads/guides/bulk-download-upload?view=bingads-12) i.e., request [Ad Group](https://docs.microsoft.com/en-us/bingads/bulk-service/ad-group?view=bingads-12) records for the account. Similarly to get all ads or keywords in an account, we recommend bulk download. By the way, for general feature requests that are not specific to the PHP SDK please see [Bing Ads Feature Suggestions](https://bingads.uservoice.com/forums/82363-bing-ads-feature-suggestions).

**Comment by timothymarois** [comment]
@eric-urban I see. Ok, I will take a look at the Bulk Download. What I really wish Bing would do is stream the data instead of using csv/xml downloads esp for reporting. It would be better to output the data back in the response of JSON primarily. But I know Bing is a long way off from making those changes. 

I didn't look at this feature request as a Bing Ads API feature, but I figured it was this SDK that didn't support it. Maybe I'm wrong on that. I will try your suggestion first.
