### ISSUE TITLE
Cannot create an abstract class when calling UpdateAdGroups()

### ISSUE THREAD

**Issue by timothymarois** [BingAds/BingAds-PHP-SDK#94]
When calling this `UpdateAdGroups()` (using the [example code](https://github.com/BingAds/BingAds-PHP-SDK/blob/dc5c8fb9f9390ab14c102fdff68cb7592091b55c/samples/V12/CampaignManagementExampleHelper.php#L1371)) 

```php
$GLOBALS['CampaignManagementProxy']->GetService()->UpdateAdGroups($request);
```

Returns the error message `Cannot create an abstract class`

**Comment by eric-urban** [comment]
@timothymarois you shared a link to the example helper library. Can you please share more details about the context e.g., where are you calling the UpdateAdGroups operation?

**Comment by timothymarois** [comment]
@eric-urban No problem. I haven't released this feature under a new package I'm working on, but I pushed to a branch to show the exact code  I'm using. 

https://github.com/Grayscale/laravel-ads-sdk/blob/master/src/Services/BingAds/Operations/AdGroupOperation.php#L170

I am able to run this just fine grabbing the details from the server itself, but I am not able to push changes to the server in the above example.

https://github.com/Grayscale/laravel-ads-sdk/blob/master/src/Services/BingAds/Operations/AdGroupOperation.php#L145

**Comment by eric-urban** [comment]
@timothymarois likely the ad group BiddingScheme is getting flagged. The SDK is leveraging SoapVar. (Please see a related [issue](https://github.com/BingAds/BingAds-PHP-SDK/issues/35).) When you create a SoapVar for any type that derives from a base/abstract type, you must encode it e.g., here. The var_dump:

```
["BiddingScheme"]=>
  object(SoapVar)#27 (4) {
    ["enc_type"]=>
    int(301)
    ["enc_value"]=>
    object(Microsoft\BingAds\V12\CampaignManagement\InheritFromParentBiddingScheme)#24 (2) {
      ["InheritedBidStrategyType"]=>
      NULL
      ["Type"]=>
      NULL
    }
    ["enc_stype"]=>
    string(30) "InheritFromParentBiddingScheme"
    ["enc_ns"]=>
    string(52) "https://bingads.microsoft.com/CampaignManagement/v12"
  }
```

Whereas the SoapVar is not encoded when you retrieve it. The var_dump:

```
["BiddingScheme"]=>
  object(stdClass)#395 (2) {
    ["Type"]=>
    string(17) "InheritFromParent"
    ["InheritedBidStrategyType"]=>
    string(9) "ManualCpc"
  }
```

I recommend that you NOT "round-trip" the returned SoapVar via GetAdGroupsByIds, and instead create a new AdGroup. [This link](https://github.com/BingAds/BingAds-PHP-SDK/blob/dc5c8fb9f9390ab14c102fdff68cb7592091b55c/samples/V12/KeywordsAds.php#L136) shows an example of encoding the ad group BiddingScheme. 

Here in the [UpdateKeywords](https://github.com/BingAds/BingAds-PHP-SDK/blob/dc5c8fb9f9390ab14c102fdff68cb7592091b55c/samples/V12/KeywordsAds.php#L502) sample we create a new Keyword object and only set the required properties.

I hope this helps,
Eric

**Comment by timothymarois** [comment]
@eric-urban Thanks for the update. this is very helpful. I will look into what you've provided here. Also when you say, create a new AdGroup instead, which is a better approach for sure, but as long as the ad group ID is being passed through, it would update existing ad groups instead of creating new on the server, ad groups without ids being passed are generating new on the server, correct?

**Comment by eric-urban** [comment]
@timothymarois yes you can update the existing ad group stored on the server. Use the Id of the AdGroup that you retrieved via GetAdGroupsByIds. For example:

```php
$updateAdGroup=new AdGroup();
$updateAdGroup->Id=$proxy->GetService()->GetAdGroupsByIds($request)->AdGroups->AdGroup[0]->Id;
// Use the $updateAdGroup object to set any other optional properties that you want to update. 
```

**Comment by timothymarois** [comment]
@eric-urban Perfect. Thanks. Are there any plans for this SDK to get a V13 anytime soon?

**Comment by eric-urban** [comment]
@timothymarois new API versions are typically released March/April each year. No firm plans have been announced yet, and I recommend that you check back for announcements via the [blog](https://blogs.msdn.microsoft.com/bing_ads_api/).
